Fix etag.hpp comment that breaks Doxygen 1.12.0
Unfortunately, "*" breaks Doxygen 1.12.0 with the following error:

    error: end of comment block while expecting command </em>

I have no idea why. Anything else like '*' or "x" works, but "*" was
clearly intended here. The best I can suggest is: * in quotes.